name: Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        description: "Choose the build status for the demo"
        type: choice
        default: success
        options:
          - success
          - failure      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      call-build: 
        uses: ./.github/workflows/o-workflow.yml
        with:
          build-status: success
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        if: needs.build.outputs.build-status == 'success'
        run: echo 'deploying'